name: chocolatine

on:
  push:
    branches:
      - '**'
      - '!ga-ignore-*'
  pull_request:
    branches:
      - '**'
      - '!ga-ignore-*'
  workflow_dispatch:

env:
  MIRROR_URL: git@github.com:TovyREN/dante.git
  EXCUTABLES: generator/generator
jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          unwanted_files=$(find . -name '*.o' -o -name '*.a' -o \
          -name '*.so' -o -name '*gcno' -o -name '*.gcda' -o -name '#*#' \
          -o -name '*~' -o -iname "*pain_au_chocolat*" -o -path *tmp/*)
          for FILE in $unwanted_files; do
            echo "::error file=${FILE#./},line=1,endline=1,title=Unwanted file detected::${FILE#./}"
          done
          if [[ -z "$unwanted_file" ]]
          then
            echo no unwanted file
          else
            exit 1
          fi
  check_program_compilation:
    needs: check_repository_cleanliness
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
      - run: make
        timeout-minutes: 2
      - run: make clean
      - run: |
            if [ -f $EXECUTABLES ]
            then
                do
            else
                done
            fi
  run_tests:
    needs: check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
      - run: make tests_run
        timeout-minutes: 2
  push_to_mirror:
    needs: check_program_compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL  }}
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}